name: Python CI with Docker and Artifactory

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build -t myapp .

      # Step 5: Log in to JFrog Artifactory
      - name: Log in to JFrog Artifactory
        run: |
          echo ${{ secrets.JFROG_API_KEY }} | docker login ${{ secrets.JFROG_URL }} -u ${{ secrets.JFROG_USERNAME }} --password-stdin

      # Step 6: Tag Docker image with Artifactory repo
      - name: Tag Docker image
        run: docker tag myapp ${{ secrets.JFROG_URL }}/docker-repo/myapp:latest

      # Step 7: Push Docker image to JFrog Artifactory
      - name: Push Docker image to Artifactory
        run: docker push ${{ secrets.JFROG_URL }}/docker-repo/myapp:latest
