name: Python CI with Docker and Artifactory

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Debugging: Print out the JFROG_URL secret to verify it's being expanded
      - name: Print JFROG_URL Secret
        run: |
          echo "JFROG_URL is: trial2ohwot.jfrog.io"

      # Step 3: Log in to JFrog Artifactory
      - name: Log in to JFrog Artifactory
        run: |
          echo ${{ secrets.JFROG_API_KEY }} | docker login trial2ohwot.jfrog.io -u ${{ secrets.JFROG_USERNAME }} --password-stdin

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t trial2ohwot.jfrog.io/artifactory/docker-repo-docker/mypythonapp .

      # Step 5: Tag Docker image with Artifactory repository name
      - name: Tag Docker image
        run: |
          echo "Tagging Docker image with: trial2ohwot.jfrog.io/artifactory/docker-repo-docker/mypythonapp"
          docker tag mypythonapp:latest trial2ohwot.jfrog.io/artifactory/docker-repo-docker/mypythonapp

      # Step 5: Push Docker image to JFrog Artifactory
      - name: Push Docker image to Artifactory
        run: |
          docker push trial2ohwot.jfrog.io/artifactory/docker-repo-docker/mypythonapp
